services:
  - type: web
    name: vehicle-maintenance-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_BV3tUpADIJz6@ep-curly-firefly-avx3fiwo.c-11.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
